// <auto-generated />
using API_consulta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_consulta.Migrations
{
    [DbContext(typeof(QueryDbContext))]
    partial class QueryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("API_consulta.Class.MedicineModel", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineAgeUse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineMg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicinePillNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicineSymptomsCure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("API_consulta.Class.PatientModel", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Comorbidity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DrugAllergy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientSex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pregnant")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatientId");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("API_consulta.Class.SymptomsModel", b =>
                {
                    b.Property<int>("SymptomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymptomsDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SymptomsGravity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymptomsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SymptomsId");

                    b.ToTable("Symptoms", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
